from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, ListFlowable
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors


def create_report(insights, filename="Nassau_Report.pdf"):
    doc = SimpleDocTemplate(filename, pagesize=A4)
    styles = getSampleStyleSheet()

    content = []

    # =========================
    # TITLE
    # =========================
    title = Paragraph(
        "<b>Nassau Candy Profitability Report</b>",
        styles["Title"]
    )
    content.append(title)
    content.append(Spacer(1, 20))

    # =========================
    # INTRO
    # =========================
    intro = Paragraph(
        "This report summarizes key business insights derived from product-level profitability analysis.",
        styles["Normal"]
    )
    content.append(intro)
    content.append(Spacer(1, 15))

    # =========================
    # HELPER FUNCTION
    # =========================
    def add_section(title_text, items):
        content.append(Paragraph(f"<b>{title_text}</b>", styles["Heading2"]))
        content.append(Spacer(1, 10))

        bullet_items = []
        for item in items:
            bullet_items.append(Paragraph(item, styles["Normal"]))

        content.append(ListFlowable(bullet_items, bulletType="bullet"))
        content.append(Spacer(1, 15))

    # =========================
    # SECTIONS (Structured Insights)
    # =========================
    if isinstance(insights, dict):
        add_section("Executive Summary", insights.get("summary", []))
        add_section("Performance Highlights", insights.get("performance", []))
        add_section("Risk Analysis", insights.get("risk", []))
        add_section("Opportunities & Recommendations", insights.get("opportunity", []))
    else:
        # fallback (if simple list passed)
        add_section("Insights", insights)

    # =========================
    # FOOTER
    # =========================
    content.append(Spacer(1, 20))
    footer = Paragraph(
        "<i>Generated by AI Analytics Dashboard</i>",
        styles["Italic"]
    )
    content.append(footer)

    # =========================
    # BUILD PDF
    # =========================
    doc.build(content)

    return filename
