from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, ListFlowable, PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import inch
import datetime


def create_report(insights, filename="Nassau_Report.pdf"):

    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=50,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    # =========================
    # CUSTOM STYLES (PRO LEVEL)
    # =========================
    title_style = ParagraphStyle(
        name="TitleStyle",
        parent=styles["Title"],
        fontSize=20,
        textColor=colors.HexColor("#1f77b4"),
        spaceAfter=20
    )

    heading_style = ParagraphStyle(
        name="HeadingStyle",
        parent=styles["Heading2"],
        textColor=colors.black,
        spaceAfter=10
    )

    normal_style = ParagraphStyle(
        name="NormalStyle",
        parent=styles["Normal"],
        fontSize=10,
        leading=14
    )

    content = []

    # =========================
    # HEADER
    # =========================
    report_date = datetime.datetime.now().strftime("%B %d, %Y")

    title = Paragraph(
        "<b>Nassau Candy Profitability Report</b>",
        title_style
    )

    subtitle = Paragraph(
        f"<i>Generated on {report_date}</i>",
        styles["Italic"]
    )

    content.append(title)
    content.append(subtitle)
    content.append(Spacer(1, 20))

    # =========================
    # EXECUTIVE NARRATIVE
    # =========================
    narrative = insights.get("narrative", "")

    if narrative:
        content.append(Paragraph("Executive Overview", heading_style))
        content.append(Spacer(1, 10))
        content.append(Paragraph(narrative, normal_style))
        content.append(Spacer(1, 20))

    # =========================
    # HELPER FUNCTION
    # =========================
    def add_section(title_text, items):
        if not items:
            return

        content.append(Paragraph(title_text, heading_style))
        content.append(Spacer(1, 8))

        bullet_items = [
            Paragraph(item, normal_style) for item in items
        ]

        content.append(ListFlowable(
            bullet_items,
            bulletType="bullet",
            leftIndent=15
        ))

        content.append(Spacer(1, 18))

    # =========================
    # SECTIONS
    # =========================
    if isinstance(insights, dict):
        add_section("Executive Summary", insights.get("summary", []))
        add_section("Performance Highlights", insights.get("performance", []))
        add_section("Risk Analysis", insights.get("risk", []))
        add_section("Opportunities & Recommendations", insights.get("opportunity", []))
    else:
        add_section("Insights", insights)

    # =========================
    # FOOTER
    # =========================
    content.append(Spacer(1, 30))

    footer = Paragraph(
        "<i>Confidential • Generated by AI Analytics Dashboard</i>",
        styles["Italic"]
    )

    content.append(footer)

    # =========================
    # BUILD PDF
    # =========================
    doc.build(content)

    return filename
